version: "3.5"

services:
  db:
    image: mysql:8.0.16
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: projappdb
      MYSQL_USER: projapp
      MYSQL_PASSWORD: projappPass
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  backend:

volumes:
  mysql_data:
